### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by nathanielmillard** [nathanielmillard/rancid-tomatillos#10]
- does the user get error messages on their interface?

**Comment by npdarrington** [comment]
I think we can implement some error message handling based on what the server may send back to us. Rather than showing the user the specific error message, it could a custom error message they see. Using `response.ok` can ensure that we catch some 4-- range errors that aren't handled inside of a catch block.

**Comment by nathanielmillard** [comment]
Thank you for that addition! 
Made it possible for more tailored error messages for a user :)
